platform :ios, '9.0'

def libs
  pod 'MaterialComponents'
end

target 'MaterialDesignSwiftIOS' do
  use_frameworks!
  libs
  target 'MaterialDesignSwiftIOSTests' do
    inherit! :search_paths
  end
  target 'MaterialDesignSwiftIOSUITests' do
    inherit! :search_paths
  end
end
